package com.app.iitdelhicampus.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "VIEW_REMINDER".
 */
public class ViewReminder {

    private String ReminderId;
    private String ClientId;
    private String ClientCode;
    private String ClientName;
    private String DealId;
    private String Name;
    private String ReferId;
    private String Refers;
    private String EmpId;
    private String ReminderType;
    private String FollowupTypeId;
    private String Activity;
    private String Desc;
    private String Status;
    private Boolean IsActive;
    private String Remarks;
    private String DueDate;
    private String ClosingDate;
    private String CreatedDate;
    private String CreatedBy;
    private String ModifiedDate;
    private String ModifiedBy;
    private Boolean _dirty;

    public ViewReminder() {
    }

    public ViewReminder(String ReminderId) {
        this.ReminderId = ReminderId;
    }

    public ViewReminder(String ReminderId, String ClientId, String ClientCode, String ClientName, String DealId, String Name, String ReferId, String Refers, String EmpId, String ReminderType, String FollowupTypeId, String Activity, String Desc, String Status, Boolean IsActive, String Remarks, String DueDate, String ClosingDate, String CreatedDate, String CreatedBy, String ModifiedDate, String ModifiedBy, Boolean _dirty) {
        this.ReminderId = ReminderId;
        this.ClientId = ClientId;
        this.ClientCode = ClientCode;
        this.ClientName = ClientName;
        this.DealId = DealId;
        this.Name = Name;
        this.ReferId = ReferId;
        this.Refers = Refers;
        this.EmpId = EmpId;
        this.ReminderType = ReminderType;
        this.FollowupTypeId = FollowupTypeId;
        this.Activity = Activity;
        this.Desc = Desc;
        this.Status = Status;
        this.IsActive = IsActive;
        this.Remarks = Remarks;
        this.DueDate = DueDate;
        this.ClosingDate = ClosingDate;
        this.CreatedDate = CreatedDate;
        this.CreatedBy = CreatedBy;
        this.ModifiedDate = ModifiedDate;
        this.ModifiedBy = ModifiedBy;
        this._dirty = _dirty;
    }

    public String getReminderId() {
        return ReminderId;
    }

    public void setReminderId(String ReminderId) {
        this.ReminderId = ReminderId;
    }

    public String getClientId() {
        return ClientId;
    }

    public void setClientId(String ClientId) {
        this.ClientId = ClientId;
    }

    public String getClientCode() {
        return ClientCode;
    }

    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    public String getClientName() {
        return ClientName;
    }

    public void setClientName(String ClientName) {
        this.ClientName = ClientName;
    }

    public String getDealId() {
        return DealId;
    }

    public void setDealId(String DealId) {
        this.DealId = DealId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getReferId() {
        return ReferId;
    }

    public void setReferId(String ReferId) {
        this.ReferId = ReferId;
    }

    public String getRefers() {
        return Refers;
    }

    public void setRefers(String Refers) {
        this.Refers = Refers;
    }

    public String getEmpId() {
        return EmpId;
    }

    public void setEmpId(String EmpId) {
        this.EmpId = EmpId;
    }

    public String getReminderType() {
        return ReminderType;
    }

    public void setReminderType(String ReminderType) {
        this.ReminderType = ReminderType;
    }

    public String getFollowupTypeId() {
        return FollowupTypeId;
    }

    public void setFollowupTypeId(String FollowupTypeId) {
        this.FollowupTypeId = FollowupTypeId;
    }

    public String getActivity() {
        return Activity;
    }

    public void setActivity(String Activity) {
        this.Activity = Activity;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public Boolean getIsActive() {
        return IsActive;
    }

    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    public String getRemarks() {
        return Remarks;
    }

    public void setRemarks(String Remarks) {
        this.Remarks = Remarks;
    }

    public String getDueDate() {
        return DueDate;
    }

    public void setDueDate(String DueDate) {
        this.DueDate = DueDate;
    }

    public String getClosingDate() {
        return ClosingDate;
    }

    public void setClosingDate(String ClosingDate) {
        this.ClosingDate = ClosingDate;
    }

    public String getCreatedDate() {
        return CreatedDate;
    }

    public void setCreatedDate(String CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    public String getCreatedBy() {
        return CreatedBy;
    }

    public void setCreatedBy(String CreatedBy) {
        this.CreatedBy = CreatedBy;
    }

    public String getModifiedDate() {
        return ModifiedDate;
    }

    public void setModifiedDate(String ModifiedDate) {
        this.ModifiedDate = ModifiedDate;
    }

    public String getModifiedBy() {
        return ModifiedBy;
    }

    public void setModifiedBy(String ModifiedBy) {
        this.ModifiedBy = ModifiedBy;
    }

    public Boolean get_dirty() {
        return _dirty;
    }

    public void set_dirty(Boolean _dirty) {
        this._dirty = _dirty;
    }

}
